title: "GeoTop-AI4MESH 2026"
short_title: "GeoTop-AI4MESH 2026"
subtitle: "In honor of the fundamental contributions of Voronoi and Delaunay"
description: >-
  GeoTop-AI4MESH 2026 is an international workshop on geometry, topology, AI-driven
  mesh generation, and simulation, held in Dalian, China, from 29 to 31
  October 2026.
lang: en
timezone: Asia/Shanghai
url: ""
baseurl: ""

markdown: kramdown
permalink: pretty

defaults:
  - scope:
      path: ""
    values:
      layout: default

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
